name: Mi primer workflow

on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Decir hola
        run: echo "Â¡Mi primer workflow funciona!"
      - name: Mostrar fecha
        run: date
